# Generated by Django 3.1.5 on 2021-01-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='cartpk', max_length=50),
            preserve_default=False,
        ),
    ]
